---
- name: Add package signing public key to keyring
  apt_key: url=http://repo.logdna.com/logdna.gpg
  when: ansible_os_family == "Debian"

- name: Add LogDNA repository
  apt_repository:
    filename: logdna
    repo: deb http://repo.logdna.com stable main
  when: ansible_os_family == "Debian"

- name: Add LogDNA repository
  yum_repository:
    name: logdna
    description: LogDNA packages
    baseurl: http://repo.logdna.com/el6/
    gpgcheck: no
  when: ansible_os_family == "RedHat"

- name: Install LogDNA agent
  apt:
    state: present
    name: logdna-agent
    allow_unauthenticated: yes
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install LogDNA agent
  yum: state=present name=logdna-agent
  when: ansible_os_family == "RedHat"

- name: Set LogDNA API Key
  command: logdna-agent -k {{ logdna_api_key }}
  when: logdna_api_key

- name: Add monitoring directories
  command: logdna-agent -d {{ item }}
  when: logdna_monitoring_directories
  with_items: logdna_monitoring_directories

- name: Add monitoring files
  command: logdna-agent -f {{ item }}
  when: logdna_monitoring_files
  with_items: logdna_monitoring_files

- name: Start LogDNA agent
  service: name=logdna-agent enabled=yes state=started
  when: logdna_api_key
